name: SlimefunBlackList
version: ${project.version}
author: StarWishsama
main: io.github.starwishsama.slimefunblacklist.SlimefunBlackList
api-version: 1.13
depend: [Slimefun]

commands:
  sfblacklist:
    aliases: sfbl
  getsfid:
    aliases: getid

permissions:
  sfblacklist.command.main:
    default: op
  sfblacklist.command.getsfid:
    default: op